apiVersion: v1
kind: Service
metadata:
  name: async-backend-service
spec:
  selector:
    component: async-backend
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  type: ClusterIP
