apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-app
  labels:
    app: celery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-app
  template:
    metadata:
      labels:
        app: celery-app
    spec:
      containers:
        - name: celery-app
          image: localhost:32000/celery_app:latest
          imagePullPolicy: Always
          env:
            - name: CELERY_BROKER_URL
              value: "amqp://guest:guest@rabbitmq-service:5672"
            - name: CELERY_RESULT_BACKEND
              value: "rpc://"
            - name: ES_USERNAME
              value: "elastic"
            - name: ES_PASSWORD
              value: "G7DCPRb+lL8Ata5gsuF7"
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 60m