apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-pv-claim
  labels:
    app: redis
    role: master
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
